def boiled (Keys,ActionChains,driver):
    ActionChains(driver).send_keys("name: Docker Image CI").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("on:").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("  push:").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys('''  branches: [ "main" ]''').perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys("pull_request:").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys('''  branches: [ "main" ]''').perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("jobs:").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("  build:").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys("    runs-on: ubuntu-latest").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys("    steps:").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("  - name: Checkout code").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("  uses: actions/checkout@v4").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys("- name: Build the Docker image").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("  run: docker build -t my-app .").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()

def workrep (time,Keys,ActionChains,driver,senior_naam,jarurat,naam,kaam):
    ActionChains(driver).send_keys("  run-"+senior_naam).perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys("    needs: "+jarurat).perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("runs-on: ubuntu-latest").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("steps:").perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("  - name:"+naam).perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys("  run: "+kaam).perform()
    ActionChains(driver).send_keys(Keys.ENTER).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    ActionChains(driver).send_keys(Keys.BACKSPACE).perform()
    time.sleep(1)
