name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t my-app .

  run-pythoncode_one1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_one.py
        run: docker run --rm my-app python3 pythoncode_one.py
  run-pythoncode_two1:
    needs: run-pythoncode_one1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_two.py
        run: docker run --rm my-app python3 pythoncode_two.py
  run-pythoncode_three1:
    needs: run-pythoncode_two1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_three.py
        run: docker run --rm my-app python3 pythoncode_three.py
  run-pythoncode_four1:
    needs: run-pythoncode_three1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_four.py
        run: docker run --rm my-app python3 pythoncode_four.py
  run-pythoncode_five1:
    needs: run-pythoncode_four1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_five.py
        run: docker run --rm my-app python3 pythoncode_five.py
  run-pythoncode_six1:
    needs: run-pythoncode_five1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_six.py
        run: docker run --rm my-app python3 pythoncode_six.py
  run-pythoncode_seven1:
    needs: run-pythoncode_six1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_seven.py
        run: docker run --rm my-app python3 pythoncode_seven.py
  run-pythoncode_eight1:
    needs: run-pythoncode_seven1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_eight.py
        run: docker run --rm my-app python3 pythoncode_eight.py
  run-pythoncode_nine1:
    needs: run-pythoncode_eight1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_nine.py
        run: docker run --rm my-app python3 pythoncode_nine.py
  run-pythoncode_ten1:
    needs: run-pythoncode_nine1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_ten.py
        run: docker run --rm my-app python3 pythoncode_ten.py
  run-pythoncode_eleven1:
    needs: run-pythoncode_ten1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_eleven.py
        run: docker run --rm my-app python3 pythoncode_eleven.py
  run-pythoncode_twelve1:
    needs: run-pythoncode_eleven1
    runs-on: ubuntu-latest
    steps:
      - name: Run pythoncode_twelve.py
        run: docker run --rm my-app python3 pythoncode_twelve.py
